from src.defs import *


MEMORY_CLEANING = 1000
ROOM_SNAPSHOT = 300
ROOM_SAFETY = 10

FILL_WITH_ENERGY = [STRUCTURE_SPAWN, STRUCTURE_EXTENSION, STRUCTURE_TOWER]
STRUCTURE_NOT_TO_HEAL = [STRUCTURE_WALL, STRUCTURE_RAMPART, STRUCTURE_ROAD, STRUCTURE_CONTAINER]
